version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "6379:6379"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stikers456
      POSTGRES_DB: pashtet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - redis

volumes:
  postgres_data:
